// Generated by CoffeeScript 1.9.1
(function() {
  $(document).ready(function() {
    return $('.story').each(function() {
      var story;
      console.log("coucou");
      return story = new StoryInterface($(this), 'p01');
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
