// Generated by CoffeeScript 1.9.1
(function() {
  $(document).ready(function() {
    return $('.story').each(function() {
      var story;
      story = new StoryInterface($(this), 'p01');
      return story.startStory();
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map
